# Generated by Django 3.2.19 on 2023-06-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errorreports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
