# Generated by Django 3.2.19 on 2023-06-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errorreports', '0002_alter_errorreport_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorReport',
        ),
    ]
