test:
  stage: build
  image: python:3.6-stretch
  script:
    - openshift/docker/build.sh
    - pip install -r requirements.txt
    - pip install -r requirements.ego.txt
    - EGO_SECRET_KEY=- python manage.py compilemessages
    - EGO_SECRET_KEY=. EGO_DEBUG=1 python manage.py test
    - pip install safety 
    - safety check -r requirements.txt 
    - safety check -r requirements.ego.txt
