variables:
  PYTHON_VERSION: '3.9'
  XAPIAN_VERSION: 1.4.19

stages:
  - test

.pip cache:
  cache:
    paths:
      - $PIP_CACHE_DIR
    when: always
  variables:
    PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip

test:
  extends:
    - .pip cache
  stage: test
  image: python:$PYTHON_VERSION
  before_script:
    - 'openshift/docker/scripts/install-xapian.sh'
    - pip install -r requirements.txt
  script:
    - python manage.py test
  variables:
    EGO_DEBUG: 1
    EGO_SECRET_KEY: .
  parallel:
    matrix:
      - PYTHON_VERSION:
          - '3.9'
          - '3.10'

security (trivy):
  stage: test
  image:
    name: aquasec/trivy
    entrypoint: [""]
  before_script:
    - cat requirements.ego.txt >> requirements.txt
  script:
    - trivy fs .
  allow_failure: true
  cache:
    paths:
      - .trivy
    when: always
  variables:
    TRIVY_CACHE_DIR: .trivy
    TRIVY_EXIT_CODE: 1
    TRIVY_SECURITY_CHECKS: vuln,config
    # This is single-run job so we do not care of k8s recommendations
    TRIVY_SKIP_FILES: openshift/jobs/reindex-extensions.yml

security (safety):
  extends:
    - .pip cache
  stage: test
  image:
    name: python:$PYTHON_VERSION
  before_script:
    - pip install safety
  script:
    - safety check -r requirements.txt
    - safety check -r requirements.ego.txt
  allow_failure: true
