image: docker:stable

variables:
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - docker info

test:
  stage: test
  tags:
    - privileged
  script:
    - docker build -f openshift/docker/Dockerfile -t extensions-web .
    - docker run -e EGO_SECRET_KEY=. -e EGO_DEBUG=1 extensions-web python manage.py test
    - docker run extensions-web bash -c 'pip install safety && safety check -r requirements.txt && safety check -r requirements.ego.txt'
