variables:
  PYTHON_VERSION: '3.9'
  XAPIAN_VERSION: '1.4.22'

workflow:
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

stages:
  - build and test
  - deploy

.pip cache:
  cache:
    paths:
      - $PIP_CACHE_DIR
    when: always
  variables:
    PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip

.test defaults:
  extends:
    - .pip cache
  stage: build and test
  image: python:$PYTHON_VERSION
  before_script:
    - 'openshift/docker/scripts/install-xapian.sh'
    - pip install -r requirements.txt
  variables:
    EGO_DEBUG: 1
    EGO_SECRET_KEY: .

test:
  extends:
    - .test defaults
  script:
    - python manage.py test
  parallel:
    matrix:
      - PYTHON_VERSION:
          - '3.9'
          - '3.10'
          - '3.11'

check migrations:
  extends:
    - .test defaults
  script:
    - python manage.py makemigrations --check

security (trivy):
  stage: build and test
  image:
    name: aquasec/trivy
    entrypoint: [""]
  before_script:
    - cat requirements.ego.txt >> requirements.txt
  script:
    - trivy fs .
  allow_failure: true
  cache:
    paths:
      - .trivy
    when: always
  variables:
    TRIVY_CACHE_DIR: .trivy
    TRIVY_EXIT_CODE: 1
    TRIVY_SCANNERS: vuln,config
    # This is single-run job so we do not care of k8s recommendations
    TRIVY_SKIP_FILES: openshift/jobs/reindex-extensions.yml

security (safety):
  extends:
    - .pip cache
  stage: build and test
  image:
    name: python:$PYTHON_VERSION
  before_script:
    - pip install safety
  script:
    - safety check -r requirements.txt
    - safety check -r requirements.ego.txt
  allow_failure: true

.build image:
  image: quay.io/gnome_infrastructure/buildah:latest
  script:
    - >-
      buildah bud
      --build-arg PYTHON_VERSION="${PYTHON_VERSION}"
      --build-arg XAPIAN_VERSION="${XAPIAN_VERSION}"
      -t quay.io/gnome_infrastructure/extensions:latest
      -f openshift/docker/Dockerfile

buildah:
  extends:
    - .build image
  stage: build and test

deploy:
  extends:
    - .build image
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "deploy"
  script:
    - !reference [.build image, script]
    - buildah login -u ${OCI_REGISTRY_USER} -p ${OCI_REGISTRY_PASSWORD} quay.io
    - buildah push quay.io/gnome_infrastructure/extensions:latest
