---
variables:
  STORAGE_DRIVER: vfs

test:
  image: fedora:32
  stage: test
  before_script:
    - dnf -y install podman-docker buildah crun fuse-overlayfs slirp4netns
    - |
      > /etc/containers/nodocker
    - buildah info
  script:
    - buildah bud --isolation chroot -f openshift/docker/Dockerfile -t extensions-web:${CI_PIPELINE_ID} .
    - buildah run --isolation chroot -e EGO_SECRET_KEY=. -e EGO_DEBUG=1 extensions-web python manage.py test
    - buildah run --isolation chroot extensions-web bash -c 'pip install safety && safety check -r requirements.txt && safety check -r requirements.ego.txt'
