# Generated by Django 3.2.19 on 2023-06-17 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0003_alter_codereview_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="codereview",
            options={
                "permissions": (
                    ("can-review-extensions", "Can review extensions"),
                    ("force-review", "Force review for reviewers"),
                    ("trusted", "Trusted author"),
                )
            },
        ),
    ]
