# Generated by Django 3.2.19 on 2023-06-17 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0004_alter_codereview_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="codereview",
            options={
                "permissions": (
                    ("can-review-extensions", "Can review extensions"),
                    ("trusted", "Trusted author"),
                )
            },
        ),
    ]
