# Generated by Codex

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("extensions", "0010_session_modes"),
        ("review", "0005_alter_codereview_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShexliResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shexli_result",
                        to="extensions.extensionversion",
                    ),
                ),
            ],
        ),
    ]
