# Generated by Django 4.2.7 on 2023-11-10 22:05

import django.core.validators
from django.db import migrations, models


def populate_data(apps, schema_editor):
    RatingComment = apps.get_model("ratings", "RatingComment")
    RatingComment.objects.filter(rating__lt=1).update(rating=0)


def revert_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_data, revert_data),
        migrations.AlterField(
            model_name="ratingcomment",
            name="rating",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
