apiVersion: batch/v1
kind: Job
metadata:
  name: reindex-extensions
spec:
  template:
    metadata:
      name: reindex-extensions
    spec:
      containers:
      - command:
        - bash
        - -c
        - |
          ls -l /extensions-web/data/xapian.db;
          rm -r /extensions-web/data/xapian.db/*;
          python /extensions-web/app/manage.py indexextensions;
          ls -l /extensions-web/data/xapian.db
        envFrom:
        - configMapRef:
            name: extensions
        - secretRef:
            name: extensions
        image: docker-registry.default.svc:5000/extensions-web/extensions-web:latest
        name: check-files
        volumeMounts:
        - mountPath: /extensions-web/www
          name: data-volume
          subPath: www
        - mountPath: /extensions-web/data
          name: data-volume
          subPath: data
      restartPolicy: Never
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: extensions-data
