# Generated by Django 3.2.13 on 2022-05-22 10:22

from django.apps.registry import Apps
from django.contrib.contenttypes.models import ContentType as ContentTypeModel
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def change_user_type(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    ContentType: ContentTypeModel = apps.get_model("contenttypes", "ContentType")
    ct = ContentType.objects.filter(app_label="auth", model="user").first()

    if ct:
        ct.app_label = "user"
        ct.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(change_user_type, elidable=True),
    ]
