# Generated by Django 3.2.19 on 2023-06-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_users_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="schedule_delete",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
