# Generated by Django 3.2.15 on 2022-08-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_users_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='display_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
