# Generated by Django 3.2.19 on 2023-06-12 18:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_schedule_delete"),
    ]

    operations = [migrations.RunSQL("DROP TABLE IF EXISTS auth_message")]
