# Generated by Django 3.2.19 on 2023-06-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="force_review",
            field=models.BooleanField(default=False),
        ),
    ]
