# Generated by Django 3.2.19 on 2023-06-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_force_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="first_name",
            new_name="display_name",
        ),
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                blank=True,
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_email_change",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
