# Generated by Django 4.2.7 on 2023-11-18 11:47

from functools import reduce
from operator import ior

from django.conf import settings
from django.db import migrations
from django.db.models import Q


def filter_display_names(apps, schema_editor):
    if settings.DISALLOWED_USERNAMES:
        User = apps.get_model("users", "User")
        User.objects.all().filter(
            reduce(
                ior,
                (
                    Q(display_name__icontains=word)
                    for word in settings.DISALLOWED_USERNAMES
                ),
            ),
        ).update(display_name="")


def revert_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_user_settings"),
    ]

    operations = [
        migrations.RunPython(filter_display_names, revert_data),
    ]
