apiVersion: v1
kind: Template
labels:
  app: extensions
  template: extensions
message: |
  The following service(s) have been created in your project: ${NAME}.

  For more information about using this template, see https://gitlab.gnome.org/Infrastructure/extensions-web.
metadata:
  annotations:
    description: GNOME Shell extensions website. For more information about using
      this template see https://gitlab.gnome.org/Infrastructure/extensions-web.
    iconClass: icon-django
    openshift.io/display-name: GNOME Shell extensions website
    openshift.io/documentation-url: https://gitlab.gnome.org/Infrastructure/extensions-web
    openshift.io/long-description: This template defines resources needed to run GNOME
      Shell extensions repository website, including a build configuration and application
      deployment configuration.  It does not include a database.
    openshift.io/provider-display-name: GNOME
    openshift.io/support-url: https://gitlab.gnome.org/Infrastructure/extensions-web/issues
    tags: gnome,python,nginx,uwsgi,extensions-web
    template.openshift.io/bindable: 'false'
  name: extensions
objects:
- apiVersion: v1
  data:
    EGO_ADMINISTRATOR_EMAIL: ${EGO_ADMINISTRATOR_EMAIL}
    EGO_ADMINISTRATOR_NAME: ${EGO_ADMINISTRATOR_NAME}
    EGO_ALLOWED_HOST: ${APPLICATION_DOMAIN}
    EGO_MEDIA_ROOT: /extensions-web/www/uploaded-files
    EGO_STATIC_ROOT: /extensions-web/www/static-files
  kind: ConfigMap
  metadata:
    name: ${NAME}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: nginx
  data:
    default.conf: |
      server {
          listen 8080 default_server;

          charset utf-8;

          sendfile on;
          tcp_nopush on;
          tcp_nodelay on;
          server_tokens off;
          client_max_body_size 16m;

          keepalive_timeout 65;

          gzip on;
          gzip_types text/css text/html text/plain application/javascript application/json application/xml;

          root /usr/share/nginx/html;

          set_real_ip_from 10.0.0.0/8;
          set_real_ip_from 172.16.0.0/12;
          set_real_ip_from 192.168.0.0/16;

          real_ip_header X-Forwarded-For;

          add_header X-Content-Type-Options nosniff;
          add_header X-Frame-Options SAMEORIGIN;

          location /healthz {
              access_log off;
              return 200;
          }

          location = /favicon.ico {
              log_not_found off;
              access_log off;
          }

          location = /robots.txt {
              allow all;
              log_not_found off;
              access_log off;
          }

          location /extension-data/ {
              alias /extensions-web/www/uploaded-files/;
          }

          location /static/ {
              location ~* \.(jpg|jpeg|gif|png|svg|ico|css|pdf|txt|bmp|js)$ {
                  access_log off;
                  expires 3d;
              }

              alias /extensions-web/www/static-files/;
          }

          location / {
              uwsgi_pass 127.0.0.1:8001;
              include uwsgi_params;
          }
      }
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${NAME}
  stringData:
    EGO_CELERY_BROKER_URL: ${EGO_CELERY_BROKER_URL}
    EGO_DATABASE_URL: ${EGO_DATABASE_URL}
    EGO_EMAIL_URL: ${EGO_EMAIL_URL}
    EGO_SECRET_KEY: ${EGO_SECRET_KEY}
- apiVersion: v1
  kind: Secret
  metadata:
    name: gnome-gitlab
  stringData:
    WebHookSecretKey: ${WEBHOOK_SECRET_KEY}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
    name: ${NAME}
  spec:
    ports:
    - name: ${NAME}
      port: 80
      targetPort: 8080
    selector:
      app: ${NAME}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${NAME}
  spec:
    host: ${APPLICATION_DOMAIN}
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: ${NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the python image
    name: python
  spec:
    tags:
    - from:
        kind: DockerImage
        name: python:3.12
      importPolicy:
        scheduled: true
      name: '3.12'
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
      template.alpha.openshift.io/wait-for-ready: 'true'
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    postCommit:
      script: bash -c 'python manage.py collectstatic --noinput && python manage.py
        test'
    source:
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: openshift/docker/Dockerfile
        env:
        - name: EGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: EGO_SECRET_KEY
              name: ${NAME}
        - name: EGO_MEDIA_ROOT
          valueFrom:
            configMapKeyRef:
              key: EGO_MEDIA_ROOT
              name: ${NAME}
        - name: EGO_STATIC_ROOT
          valueFrom:
            configMapKeyRef:
              key: EGO_STATIC_ROOT
              name: ${NAME}
        forcePull: true
        from:
          kind: ImageStreamTag
          name: python:3.12
      type: Docker
    triggers:
    - type: ImageChange
    - type: ConfigChange
    - gitlab:
        secretReference:
          name: gnome-gitlab
      type: GitLab
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${NAME}-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 3096Mi
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      alpha.image.policy.openshift.io/resolve-names: '*'
      app.openshift.io/route-disabled: "false"
      image.openshift.io/triggers: >-
        [{"from":{"kind":"ImageStreamTag","name":"${NAME}:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"extensions\")].image"}]
    name: ${NAME}
  spec:
    progressDeadlineSeconds: 600
    replicas: ${REPLICAS}
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: ${NAME}
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: ${NAME}
          deployment: ${NAME}
      spec:
        containers:
        - image: ghcr.io/nginxinc/nginx-unprivileged:stable-alpine-slim
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: nginx
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          volumeMounts:
          - mountPath: /extensions-web/www
            name: extensions-data
            subPath: www
          - mountPath: /etc/nginx/conf.d/default.conf
            name: nginx
            subPath: default.conf
        - envFrom:
          - configMapRef:
              name: ${NAME}
          - secretRef:
              name: ${NAME}
          image: ${DEFAULT_DOCKER_REGISTRY}/${NAME}/${NAME}:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8001
            timeoutSeconds: 1
          name: extensions
          ports:
          - containerPort: 8001
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8001
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8001
            timeoutSeconds: 1
          volumeMounts:
          - mountPath: /extensions-web/www
            name: extensions-data
            subPath: www
          - mountPath: /extensions-web/data
            name: extensions-data
            subPath: data
          - mountPath: /extensions-web/tmp
            name: extensions-data
            subPath: tmp
        volumes:
        - name: extensions-data
          persistentVolumeClaim:
            claimName: ${NAME}-data
        - configMap:
            defaultMode: 420
            name: nginx
          name: nginx
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      alpha.image.policy.openshift.io/resolve-names: '*'
      image.openshift.io/triggers: >-
        [{"from":{"kind":"ImageStreamTag","name":"${NAME}:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"celery-worker\")].image"}]
    name: ${NAME}-celery-worker
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: ${NAME}-celery-worker
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: ${NAME}-celery-worker
          deployment: ${NAME}-celery-worker
      spec:
        containers:
        - args:
          - -A
          - sweettooth
          - worker
          - --loglevel=INFO
          command:
          - celery
          envFrom:
          - configMapRef:
              name: ${NAME}
          - secretRef:
              name: ${NAME}
          image: ${DEFAULT_DOCKER_REGISTRY}/${NAME}/${NAME}:latest
          imagePullPolicy: IfNotPresent
          name: celery-worker
          volumeMounts:
          - mountPath: /extensions-web/www
            name: extensions-data
            subPath: www
          - mountPath: /extensions-web/data
            name: extensions-data
            subPath: data
          - mountPath: /extensions-web/tmp
            name: extensions-data
            subPath: tmp
        volumes:
        - name: extensions-data
          persistentVolumeClaim:
            claimName: ${NAME}-data
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      alpha.image.policy.openshift.io/resolve-names: '*'
      image.openshift.io/triggers: >-
        [{"from":{"kind":"ImageStreamTag","name":"${NAME}:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"celery-beat\")].image"}]
    name: ${NAME}-celery-beat
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: ${NAME}-celery-beat
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${NAME}-celery-beat
          deployment: ${NAME}-celery-beat
      spec:
        containers:
        - args:
          - -A
          - sweettooth
          - beat
          - --loglevel=INFO
          command:
          - celery
          envFrom:
          - configMapRef:
              name: ${NAME}
          - secretRef:
              name: ${NAME}
          image: ${DEFAULT_DOCKER_REGISTRY}/${NAME}/${NAME}:latest
          imagePullPolicy: IfNotPresent
          name: celery-beat
          volumeMounts:
          - mountPath: /extensions-web/www
            name: extensions-data
            subPath: www
          - mountPath: /extensions-web/data
            name: extensions-data
            subPath: data
          - mountPath: /extensions-web/tmp
            name: extensions-data
            subPath: tmp
        volumes:
        - name: extensions-data
          persistentVolumeClaim:
            claimName: ${NAME}-data
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: job-update-popularity
  spec:
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - command:
              - python
              - manage.py
              - update_popularity
              envFrom:
              - configMapRef:
                  name: ${NAME}
              - secretRef:
                  name: ${NAME}
              image: ${DEFAULT_DOCKER_REGISTRY}/${NAME}/${NAME}:latest
              name: update-popularity
            restartPolicy: Never
    schedule: 0 0 * * *
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: job-clean-users
  spec:
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - command:
              - python
              - manage.py
              - clean_users
              envFrom:
              - configMapRef:
                  name: ${NAME}
              - secretRef:
                  name: ${NAME}
              image: ${DEFAULT_DOCKER_REGISTRY}/${NAME}/${NAME}:latest
              name: clean-users
            restartPolicy: Never
    schedule: 20 0 * * *
parameters:
- description: The name assigned to all of the application objects defined in this
    template.
  displayName: Name
  name: NAME
  required: true
  value: extensions
- description: Number of application replicas.
  displayName: Replicas
  name: REPLICAS
  required: true
  value: '3'
- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  required: true
  value: openshift
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 2048Mi
- description: The URL of the repository with your application source code.
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://gitlab.gnome.org/Infrastructure/extensions-web.git
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
  displayName: Git Reference
  name: SOURCE_REPOSITORY_REF
- description: The exposed hostname that will route to the extensions-web service,
    if left blank a value will be defaulted.
  displayName: Application Hostname
  name: APPLICATION_DOMAIN
  value: ''
- description: Administrator name.
  displayName: Administrator name
  name: EGO_ADMINISTRATOR_NAME
  value: ''
- description: Email of administator. For error notifications.
  displayName: Administator email
  name: EGO_ADMINISTRATOR_EMAIL
  value: ''
- description: Database URL in format suitable for dj-database-url
  displayName: Database URL
  name: EGO_DATABASE_URL
  value: ''
- description: Email URL in format suitable for dj-email-url
  displayName: Email URL
  name: EGO_EMAIL_URL
  value: ''
- description: Celery broker URL
  displayName: Celery broker URL
  name: EGO_CELERY_BROKER_URL
  value: ''
- description: Django secret key.
  displayName: Django secret key
  name: EGO_SECRET_KEY
  value: ''
- description: Secret key for GNOME Gitlab.
  displayName: WebHook secret key
  name: WEBHOOK_SECRET_KEY
  value: ''
- description: URL of private docker registry. Usually docker-registry.default.svc:5000.
  displayName: Docker registry.
  name: DEFAULT_DOCKER_REGISTRY
  value: docker-registry.default.svc:5000
