# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-16 21:01
from __future__ import unicode_literals

from django.db import migrations, models

import sweettooth.extensions.models


class Migration(migrations.Migration):
    dependencies = [
        ("extensions", "0002_auto_20161027_1641"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extension",
            name="icon",
            field=models.ImageField(
                blank=True,
                default=b"",
                upload_to=sweettooth.extensions.models.make_icon_filename,
            ),
        ),
    ]
