# Generated by Django 2.2.7 on 2019-11-23 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extensions", "0005_auto_20190112_1733"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extension",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
