# Generated by Django 2.2.13 on 2020-12-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extensions", "0006_auto_20191123_2146"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shellversion",
            name="minor",
            field=models.IntegerField(),
        ),
    ]
