# Generated by Django 2.2.17 on 2021-02-25 12:48

from django.db import migrations

import sweettooth.extensions.fields


class Migration(migrations.Migration):
    dependencies = [
        ("extensions", "0007_auto_20201219_2046"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extension",
            name="url",
            field=sweettooth.extensions.fields.HttpURLField(blank=True),
        ),
    ]
