# Generated by Django 3.2.11 on 2022-03-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0009_shell40_minor_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='session_unlock_dialog',
            field=models.BooleanField(default=False),
        ),
    ]
