# Generated by Django 3.2.14 on 2022-08-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extensions", "0010_session_modes"),
    ]

    operations = [
        migrations.AddField(
            model_name="extension",
            name="allow_comments",
            field=models.BooleanField(default=True),
        ),
    ]
