# Generated by Django 3.2.15 on 2022-09-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extensions", "0011_extension_allow_comments"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="extensionversion",
            index=models.Index(
                fields=["extension", "status"], name="extension_id__status_idx"
            ),
        ),
    ]
