# Generated by Django 2.2.12 on 2020-05-23 12:43

import os

from datetime import datetime

from django.db import migrations, models

def populate_data(apps, schema_editor):
    Extension = apps.get_model("extensions", "Extension")
    ExtensionVersion = apps.get_model("extensions", "ExtensionVersion")

    Extension.objects.all().update(updated=models.F('created'))

    for version in ExtensionVersion.objects.all():
        # We don't have better choise than mtime now
        try:
            version.created = datetime.fromtimestamp(
                os.path.getmtime(
                    version.source.storage.path(version.source.name)
                )
            )
            version.save()
        except FileNotFoundError:
            pass

        if version.created and version.extension.updated < version.created:
            version.extension.updated = version.created
            version.extension.save()

def revert_data(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0012_auto_20200511_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='updated',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='extensionversion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RunPython(populate_data, revert_data),
    ]
