# Generated by Django 3.2.19 on 2023-06-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extensions", "0013_donationurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationurl",
            name="url_type",
            field=models.CharField(
                choices=[
                    ("buymeacoffee", "Buy Me a Coffee"),
                    ("custom", "Link"),
                    ("github", "GitHub"),
                    ("kofi", "Ko-fi"),
                    ("patreon", "Patreon"),
                    ("paypal", "PayPal"),
                ],
                default="custom",
                max_length=32,
            ),
        ),
    ]
