# Generated by Django 3.2.21 on 2023-09-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extensions", "0015_alter_bigint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationurl",
            name="url_type",
            field=models.CharField(
                choices=[
                    ("buymeacoffee", "Buy Me a Coffee"),
                    ("custom", "Link"),
                    ("github", "GitHub"),
                    ("kofi", "Ko-fi"),
                    ("liberapay", "Liberapay"),
                    ("opencollective", "Open Collective"),
                    ("patreon", "Patreon"),
                    ("paypal", "PayPal"),
                ],
                default="custom",
                max_length=32,
            ),
        ),
    ]
