# Generated by Django 3.2.15 on 2022-09-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0016_extension_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionversion',
            name='license',
            field=models.CharField(choices=[('Apache-2.0', 'Apache 2.0'), ('BSD-2-Clause', '2-Clause BSD'), ('BSD-3-Clause', '3-Clause BSD'), ('EPL-2.0', 'EPL 2.0'), ('GPL-2.0', 'GPL 2.0'), ('GPL-2.0 or later', 'Gpl20Orlater'), ('GPL-3.0', 'GPL 2.0 or later'), ('GPL-3.0-or-later', 'GPL 3.0 or later'), ('MIT', 'MIT'), ('MPL-2.0', 'MPL 2.0')], default='GPL-2.0', max_length=24),
        ),
    ]
