# Generated by Django 3.2.22 on 2023-10-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extensions", "0016_alter_donationurl_url_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="donationurl",
            index=models.Index(
                fields=["extension", "url_type"], name="extension_id__url_type_idx"
            ),
        ),
    ]
