# Generated by Django 3.2.21 on 2023-10-26 05:05

from django.db import migrations, models

import sweettooth.extensions.models


class Migration(migrations.Migration):
    dependencies = [
        ("extensions", "0017_donationurl_extension_id__url_type_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="extensionversion",
            name="version_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=16,
                null=True,
                validators=[sweettooth.extensions.models.version_name_validator],
            ),
        ),
    ]
