# Generated by Django 2.2.12 on 2020-05-11 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extensions", "0018_extensionversion_version_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extension",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="extensions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
