# Generated by Django 2.2.12 on 2020-05-23 12:43

import os
from datetime import datetime

from django.db import migrations, models


def populate_data(apps, schema_editor):
    Extension = apps.get_model("extensions", "Extension")
    Extension.objects.all().update(updated=models.F("created"))

    for extension in Extension.objects.all():
        for version in extension.versions.all():
            # We don't have better choise than mtime now
            try:
                version.created = datetime.fromtimestamp(
                    os.path.getmtime(version.source.storage.path(version.source.name))
                )
                version.save()
            except Exception:
                pass

            if version.created and extension.updated < version.created:
                extension.updated = version.created
                extension.save()


def revert_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("extensions", "0019_auto_20200511_1019"),
    ]

    operations = [
        migrations.AddField(
            model_name="extension",
            name="updated",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="extensionversion",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RunPython(populate_data, revert_data),
    ]
