# Generated by Django 2.2.12 on 2020-05-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extensions", "0020_auto_20200523_1243"),
    ]

    operations = [
        migrations.AddField(
            model_name="extension",
            name="recommended",
            field=models.BooleanField(default=False),
        ),
    ]
